package com.ekainano.translation.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a historical or user-verified translation entry stored locally on the device ledger.
 * This entity supports full offline capabilities, caching AI baselines, human corrections,
 * linguistic particle breakdowns, and cloud synchronization status.
 */
@Entity(tableName = "translations")
data class TranslationEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "direction")
    val direction: String, // e.g., "GIL ➔ EN" or "EN ➔ GIL"

    @ColumnInfo(name = "source_text")
    val sourceText: String, // The original input phrase

    @ColumnInfo(name = "raw_baseline")
    val rawBaseline: String, // The initial translation generated by the AI model

    @ColumnInfo(name = "edited_translation")
    val editedTranslation: String, // The human-verified or corrected final translation

    @ColumnInfo(name = "structural_breakdown")
    val structuralBreakdown: String, // Grammatical analysis of core particles (e, n, ia, etc.)

    @ColumnInfo(name = "cultural_notes")
    val culturalNotes: String, // Cultural context, dialect variations, or stylistic nuances

    @ColumnInfo(name = "contributor_email")
    val contributorEmail: String, // The authenticated Gmail address of the contributor

    @ColumnInfo(name = "timestamp")
    val timestamp: Long = System.currentTimeMillis(), // Record creation time for ordering

    @ColumnInfo(name = "is_synced")
    val isSynced: Boolean = false // Track whether the local ledger entry has uploaded to the cloud
)